ENT.Base = "nut_readerbase"
ENT.Type = "anim"
ENT.PrintName = "Magnetic Card Reader - Level 3"
ENT.Author = "La Corporativa"
ENT.Spawnable = true
ENT.AdminOnly = true
ENT.Category = "NutScript"
ENT.Level = "Level 1"
ENT.Cards = {"admkey", "nuckey"}
